WIP: Add ESP32 support
cloud4rpi/docs pull request #28
Opened 2019-05-27 10:56 UTC by Himura2la

2019-05-29 05:33 UTC, dirk-pieterse requested changes

2019-05-29 05:33 UTC, dirk-pieterse commented on README.md
> +The documentation is created with [MkDocs](http://www.mkdocs.org/). If you need to open it locally do the following:
```suggestion
The documentation is created with [MkDocs](http://www.mkdocs.org/). Follow the steps below to open it locally. 
```

2019-05-29 05:33 UTC, dirk-pieterse commented on README.md
> +- Install [MkDocs](http://www.mkdocs.org/#installation) and [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) using the `pip install mkdocs mkdocs-material` command.
```suggestion
- Use the `pip install mkdocs mkdocs-material` command to install [MkDocs](http://www.mkdocs.org/#installation) and [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/).
```

2019-05-29 05:33 UTC, dirk-pieterse commented on README.md
> +While **MkDocs** is running, you should be able to access the documentation using the [http://127.0.0.1:8000](http://127.0.0.1:8000) URL.
```suggestion
While **MkDocs** is running, use the [http://127.0.0.1:8000](http://127.0.0.1:8000) URL to access the documentation.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
>  Frequently asked questions and possible issues you may face when working with [Cloud4RPi](https://cloud4rpi.io):
```suggestion
Frequently asked questions and possible issues you can encounter with [Cloud4RPi](https://cloud4rpi.io):
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
>  The `InsecurePlatformWarning: A true SSLContext object is not available...` notification appears when you run Cloud4RPi on a Python v2.7.9 and earlier. Use the following command to check the Python v
```suggestion
The `InsecurePlatformWarning: A true SSLContext object is not available...` notification appears when you run Cloud4RPi on Python v2.7.9 and earlier. Use the following command to check the Python version:
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
>  You can use [one of the following approaches](https://docs.python.org/2/using/index.html) to install the latest version.
```suggestion
You can use [one of the following approaches](https://docs.python.org/2/using/index.html) to install the latest version:
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
>  Use one of the following commands to read the logs containing the service's output and errors:
```suggestion
Use one of the following commands to read the logs that contain the service's output and errors:
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
> +The `Multiple libraries were found for "WiFi.h"` message may appear in Arduino IDE, which means the IDE has two libraries with the same name, and it can not decide which of them to use.
```suggestion
The `Multiple libraries were found for "WiFi.h"` message can appear in Arduino IDE. This indicates the IDE has two libraries with the same name, and it does not know which one to use.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
> +You can avoid this error by specifying the absolute path to the header file in the `#include` directive, for example, like this:
```suggestion
To avoid this error, specify the absolute path to the header file in the `#include` directive, for example:
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/faq.md
> +The valid path to both libraries appear in the error message, you can copy-paste it. Remember to add the `src\` subfolder between the library path and header file name.
```suggestion
You can copy-paste the valid path to both libraries that appear in the error message. Add the `src\` subfolder between the library path and header file name.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/index.md
>  Currently, we provide detailed instructions and examples for the following platforms and languages:
```suggestion
Detailed instructions and examples are available for the following platforms and languages:
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/index.md
>      Both Python 2 and Python 3 are supported.
```suggestion
    Python 2 and Python 3 are supported.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/index.md
>  [Contact us](https://cloud4rpi.answerdesk.io/) if your device or preferred language is not listed, we are here to help.
```suggestion
[Contact us](https://cloud4rpi.answerdesk.io/) if your device or preferred language is not listed.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
> +1. Open **Arduino** and select your board in the **Tools** | **Board** menu. Add [ESP8266](https://github.com/esp8266/Arduino#installing-with-boards-manager) or [ESP32](https://github.com/espressif/a
'if required' Why else would you do it if it is not required?

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-pio.md
>  9. Once flashing is complete, open `Serial Monitor` and watch the sample code's output.
```suggestion
9. Once flashing is complete, the `Serial Monitor` shows the [device](https://cloud4rpi.io/devices) went online and started to send data
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-pio.md
> +5. Copy-paste the sample code ([ESP8266](https://github.com/cloud4rpi/cloud4rpi-esp-arduino/blob/master/examples/ESP8266/ESP8266.ino), [ESP32](https://github.com/cloud4rpi/cloud4rpi-esp-arduino/blob/
```suggestion
5. Copy-paste the sample code ([ESP8266](https://github.com/cloud4rpi/cloud4rpi-esp-arduino/blob/master/examples/ESP8266/ESP8266.ino), [ESP32](https://github.com/cloud4rpi/cloud4rpi-esp-arduino/blob/master/examples/ESP32/ESP32.ino)).
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-pio.md
> +7. If the `LED_BUILTIN` constant is not defined in your board's library, change this constant to the pin number to which an LED is connected (for example, `2`).
```suggestion
7. If the `LED_BUILTIN` constant is not defined in your board's library, change this constant to the LED's pin number (for example, `2`).
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
>  3. Install **ArduinoJson** and **PubSubClient** libraries. You should do it manually because the **Library Manager** does not manage package dependencies.
```suggestion
3. Install **ArduinoJson** and **PubSubClient** libraries. The **Library Manager** does not manage package dependencies.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
>  2. Install the Cloud4RPi library from the **Library Manager** by opening the **Sketch** | **Include Library** | **Manage Libraries** menu, entering `cloud4rpi` into the search field and installing th
Why 'entering' and 'installing'?

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
>  2. Install the Cloud4RPi library from the **Library Manager** by opening the **Sketch** | **Include Library** | **Manage Libraries** menu, entering `cloud4rpi` into the search field and installing th
```suggestion
2. Install the Cloud4RPi library from the **Library Manager**. To do this, open the **Sketch** | **Include Library** | **Manage Libraries** menu, enter `cloud4rpi` into the search field and install the **cloud4rpi-esp-arduino** package.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
> +    3. [Optional] Open the `%HOMEPATH%\Documents\Arduino\libraries\cloud4rpi-esp-arduino\src\Cloud4RPi.h` (`~/Documents/Arduino/libraries/cloud4rpi-esp-arduino/src/Cloud4RPi.h` on Mac) file and enabl
```suggestion
    3. [Optional] Open the `%HOMEPATH%\Documents\Arduino\libraries\cloud4rpi-esp-arduino\src\Cloud4RPi.h` (`~/Documents/Arduino/libraries/cloud4rpi-esp-arduino/src/Cloud4RPi.h` on Mac) file and add the `#define CLOUD4RPI_DEBUG 1` line at the beginning to enable verbose output.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
> +5. Open the sample code using the **File** | **Examples** | **cloud4rpi-esp-arduino** menu item. Restart Arduino IDE if this item did not appear.
```suggestion
5. Use the **File** | **Examples** | **cloud4rpi-esp-arduino** menu item to open the sample code. Restart Arduino IDE if this item does not appear.
```

2019-05-29 05:33 UTC, dirk-pieterse commented on docs/start/esp-ino.md
> +7. If the `LED_BUILTIN` constant is not defined in your board's library, change this constant to the pin number to which an LED is connected (for example, `2`).
```suggestion
7. If the `LED_BUILTIN` constant is not defined in your board's library, change this constant to the LED's pin number (for example, `2`).
```

2019-05-29 06:56 UTC, sky3d commented on docs/faq.md
> +## How to avoid WiFi library collision on Arduino?
It's mean "Arduino IDE" not framework. May be better to use non-official name?

2019-05-29 06:56 UTC, sky3d commented on docs/start/esp-ino.md
> +
Where is step #7  (Network credentials) ?

2019-05-29 14:51 UTC, Himura2la commented on docs/start/esp-ino.md
> +
In the previous section

2019-05-30 11:56 UTC, sky3d approved these changes

2019-07-24 08:26 UTC, merged